// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Sugerencias de asignación de turnos impulsadas por IA.
 *
 * - suggestShiftAssignments - Una función que proporciona sugerencias de asignación de turnos impulsadas por IA.
 * - SuggestShiftAssignmentsInput - El tipo de entrada para la función suggestShiftAssignments.
 * - SuggestShiftAssignmentsOutput - El tipo de retorno para la función suggestShiftAssignments.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestShiftAssignmentsInputSchema = z.object({
  messengerAvailability: z
    .string()
    .describe('Una lista de la disponibilidad de los mensajeros, incluyendo sus horas de trabajo y días libres.'),
  shiftRequirements: z
    .string()
    .describe('Una descripción de los requisitos del turno, incluyendo hora, lugar y habilidades requeridas.'),
  otherConstraints: z
    .string()
    .describe('Cualquier otra restricción que deba tenerse en cuenta, como horas máximas de trabajo o ubicaciones preferidas.'),
});

export type SuggestShiftAssignmentsInput = z.infer<
  typeof SuggestShiftAssignmentsInputSchema
>;

const SuggestShiftAssignmentsOutputSchema = z.object({
  suggestedAssignments: z
    .string()
    .describe('Una lista de asignaciones de turnos sugeridas, incluyendo el nombre del mensajero, la hora del turno y la ubicación.'),
  reasoning: z
    .string()
    .describe('La justificación detrás de las asignaciones sugeridas, incluyendo los factores que se tuvieron en cuenta.'),
});

export type SuggestShiftAssignmentsOutput = z.infer<
  typeof SuggestShiftAssignmentsOutputSchema
>;

export async function suggestShiftAssignments(
  input: SuggestShiftAssignmentsInput
): Promise<SuggestShiftAssignmentsOutput> {
  return suggestShiftAssignmentsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestShiftAssignmentsPrompt',
  input: {schema: SuggestShiftAssignmentsInputSchema},
  output: {schema: SuggestShiftAssignmentsOutputSchema},
  prompt: `Eres un asistente de IA que proporciona sugerencias para la asignación de turnos basándose en la disponibilidad de los mensajeros, los requisitos de los turnos y otras restricciones.

Disponibilidad de Mensajeros: {{{messengerAvailability}}}
Requisitos de los Turnos: {{{shiftRequirements}}}
Otras Restricciones: {{{otherConstraints}}}

Sugiere asignaciones de turnos que optimicen la eficiencia y minimicen los conflictos. Explica tu razonamiento para cada sugerencia.

Formatea tu respuesta como un objeto JSON con los campos 'suggestedAssignments' y 'reasoning'. 'suggestedAssignments' debe ser una lista con los nombres de los mensajeros, los horarios de los turnos y las ubicaciones. 'reasoning' debe ser una breve explicación de la asignación.
`,
});

const suggestShiftAssignmentsFlow = ai.defineFlow(
  {
    name: 'suggestShiftAssignmentsFlow',
    inputSchema: SuggestShiftAssignmentsInputSchema,
    outputSchema: SuggestShiftAssignmentsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
